import { useCallback } from 'react';
import { useSettingsStore } from '../stores/useSettingsStore';

const copy = {
  en: {
    'tabs.home': 'Home',
    'tabs.device': 'Device',
    'tabs.control': 'Control',
    'tabs.mission': 'Missions',
    'tabs.settings': 'Settings',
    'home.title': 'Overview',
    'home.subtitle': 'Robot operations',
    'home.noRobot': 'No robot connected',
    'home.noRobotHint': 'Connect a robot or enter demo mode to view live operations.',
    'home.connect': 'Connect device',
    'home.robot': 'Current robot',
    'home.demoRobot': 'Demo robot',
    'home.online': 'Online',
    'home.offline': 'Offline',
    'home.battery': 'Battery',
    'home.network': 'Connection',
    'home.networkStable': 'Stable',
    'home.mode': 'Mode',
    'home.modeManual': 'Manual',
    'home.modeIdle': 'Idle',
    'home.modeMission': 'Inspection',
    'home.modeInspectionReady': 'Inspection ready',
    'home.modeMapping': 'Mapping',
    'home.modeLocalization': 'Localization ready',
    'home.modeNavigation': 'Point navigation',
    'home.modeRouteRecording': 'Route recording',
    'home.modeTransitioning': 'Switching mode',
    'home.modeError': 'Mode error',
    'home.modeUnknown': 'Unknown',
    'home.localization': 'Localization',
    'home.localized': 'Ready',
    'home.localizationUnknown': 'Unknown',
    'home.currentMission': 'Current mission',
    'home.noMission': 'No active mission',
    'home.noMissionHint': 'The robot is ready for a new route.',
    'home.startMission': 'Start inspection',
    'home.manageMission': 'Manage',
    'home.liveViews': 'Live workspace',
    'home.map': 'Live map',
    'home.mapHint': 'Position and surroundings',
    'home.video': 'Live video',
    'home.videoHint': 'Camera monitoring',
    'home.quickActions': 'Quick actions',
    'home.manualControl': 'Manual control',
    'home.manageDevice': 'Device details',
    'home.systemHealthy': 'System ready',
    'home.systemHealthyHint': 'No active robot or mission warnings.',
    'home.warning': 'Attention required',
    'home.viewAlerts': 'View',
    'device.title': 'Devices',
    'device.subtitle': 'Connections and pairing',
    'device.active': 'Active device',
    'device.connectedVia': 'Connected via {{transport}}',
    'device.disconnect': 'Disconnect',
    'device.add': 'Connect a robot',
    'device.addHint': 'Enter the address shown by the robot gateway. The protocol is detected automatically.',
    'device.demo': 'Explore with a demo robot',
    'device.demoHint': 'Preview maps, telemetry and controls without moving hardware.',
    'device.openDemo': 'Open demo',
    'device.guide': 'Connection help',
    'alerts.title': 'Alerts',
    'alerts.subtitle': 'Robot and mission events',
    'alerts.none': 'Everything looks good',
    'alerts.noneHint': 'There are no active warnings from the robot or current mission.',
    'alerts.offline': 'Robot offline',
    'alerts.offlineHint': 'Live status and commands are unavailable until a device reconnects.',
    'common.back': 'Back',
  },
  zh: {
    'tabs.home': '首页',
    'tabs.device': '设备',
    'tabs.control': '控制',
    'tabs.mission': '任务',
    'tabs.settings': '设置',
    'home.title': '运行总览',
    'home.subtitle': '机器人控制台',
    'home.noRobot': '尚未连接机器人',
    'home.noRobotHint': '连接机器人或进入演示模式，即可查看实时运行状态。',
    'home.connect': '连接设备',
    'home.robot': '当前机器人',
    'home.demoRobot': '演示机器人',
    'home.online': '在线',
    'home.offline': '离线',
    'home.battery': '电量',
    'home.network': '连接',
    'home.networkStable': '稳定',
    'home.mode': '当前模式',
    'home.modeManual': '手动控制',
    'home.modeIdle': '空闲',
    'home.modeMission': '巡检任务',
    'home.modeInspectionReady': '巡检待命',
    'home.modeMapping': '建图',
    'home.modeLocalization': '定位待命',
    'home.modeNavigation': '单点导航',
    'home.modeRouteRecording': '路线录制',
    'home.modeTransitioning': '模式切换中',
    'home.modeError': '模式异常',
    'home.modeUnknown': '未知',
    'home.localization': '定位',
    'home.localized': '正常',
    'home.localizationUnknown': '未知',
    'home.currentMission': '当前任务',
    'home.noMission': '暂无进行中的任务',
    'home.noMissionHint': '机器人已准备好，可以选择路线开始巡检。',
    'home.startMission': '开始巡检',
    'home.manageMission': '管理任务',
    'home.liveViews': '实时工作区',
    'home.map': '实时地图',
    'home.mapHint': '位置与周边环境',
    'home.video': '实时视频',
    'home.videoHint': '查看摄像头画面',
    'home.quickActions': '快捷操作',
    'home.manualControl': '手动控制',
    'home.manageDevice': '设备详情',
    'home.systemHealthy': '系统状态正常',
    'home.systemHealthyHint': '当前没有机器人或任务告警。',
    'home.warning': '需要处理',
    'home.viewAlerts': '查看',
    'device.title': '设备',
    'device.subtitle': '机器人连接与安全配对',
    'device.active': '当前设备',
    'device.connectedVia': '通过 {{transport}} 连接',
    'device.disconnect': '断开连接',
    'device.add': '连接机器人',
    'device.addHint': '输入机器人网关显示的地址，APP 会自动识别连接协议。',
    'device.demo': '体验演示机器人',
    'device.demoHint': '无需连接真实设备，即可预览地图、状态与控制工作区。',
    'device.openDemo': '进入演示',
    'device.guide': '连接帮助',
    'alerts.title': '告警中心',
    'alerts.subtitle': '机器人与任务异常',
    'alerts.none': '当前运行正常',
    'alerts.noneHint': '机器人和当前任务没有需要处理的告警。',
    'alerts.offline': '机器人已离线',
    'alerts.offlineHint': '重新连接设备前，实时状态和控制指令不可用。',
    'common.back': '返回',
  },
} as const;

export type ProductCopyKey = keyof typeof copy.en;

export function useProductCopy() {
  const language = useSettingsStore((s) => s.language);
  const pc = useCallback((key: ProductCopyKey, params?: Record<string, string | number>) => {
    let value: string = copy[language][key] ?? copy.en[key] ?? key;
    Object.entries(params ?? {}).forEach(([name, replacement]) => {
      value = value.replaceAll(`{{${name}}}`, String(replacement));
    });
    return value;
  }, [language]);
  return { pc, language };
}
